service: ec2-controlplane-lambda

plugins:
  - serverless-pseudo-parameters
  
provider:
  name: aws
  runtime: python3.6

  stage: ${opt:stage, 'dev'}  
  region: ap-southeast-1
  
  iamRoleStatements:
      - Effect: Allow
        Action:
          - ec2:Stop*
          - ec2:Start*
        Resource: "arn:aws:ec2:#{AWS::Region}:#{AWS::AccountId}:instance/*"
      - Effect: Allow
        Action:
          - ec2:Describe*
        Resource: "*"
      - Effect: Allow
        Action: 
          - autoscaling:UpdateAutoScalingGroup
        Resource: "arn:aws:autoscaling:#{AWS::Region}:#{AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*"

functions:
  ec2start:
    handler: handler.ec2start
    memorySize: 128
    timeout: 5
    events:
      - schedule: 
          description: 'Run at 9am GMT+8 Mon-Fri'
          rate: cron(0 1 ? * MON-FRI *)
          enabled: true

  ec2stop:
    handler: handler.ec2stop
    memorySize: 128
    timeout: 5
    events:
      - schedule: 
          description: 'Run at 7pm GMT+8 Mon-Fri'
          rate: cron(0 11 ? * MON-FRI *)
          enabled: true

  stop-asg:
    handler: handler.setasginstancesize
    memorySize: 128
    timeout: 5
    events:
      - schedule: 
          description: 'Run at 7pm GMT+8 Mon-Fri'
          rate: cron(0 11 ? * MON-FRI *)
          enabled: true
          input:
            AsgGroupName: sitapp-AutoScaleGrp-XL7APL96YQPQ
            MinSize: 0
            DesiredCapacity: 0

  start-asg:
    handler: handler.setasginstancesize
    memorySize: 128
    timeout: 5
    events:
      - schedule: 
          description: 'Run at 9am GMT+8 Mon-Fri'
          rate: cron(0 1 ? * MON-FRI *)
          enabled: true
          input:
            AsgGroupName: sitapp-AutoScaleGrp-XL7APL96YQPQ
            MinSize: 1
            DesiredCapacity: 1
